### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.10.0-2-amd64 (x86_64)

### ISSUE THREAD

**Issue by robinbuhtig** [rockyprabowo/rtl8821CU#1]
user@machine:~/build$ sudo dkms build -m ${DRV_NAME} -v ${DRV_VERSION}

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'make' -j12 KVER=5.10.0-2-amd64...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.10.0-2-amd64 (x86_64)
Consult /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/make.log for more information.
user@machine:~/build$ 

''''/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/make.log'''''''
DKMS make.log for rtl8821CU-5.4.1_28754.r1 for kernel 5.10.0-2-amd64 (x86_64)
Fri 29 Jan 2021 05:32:17 PM HKT
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.10.0-2-amd64/build M=/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.10.0-2-amd64'
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_io.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_query.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_set.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ieee80211.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mi.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_wlan_util.o
  CC [M]  /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_vht.o
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_debug.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_cmd.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_debug.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_cmd.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_security.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_security.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_io.c:47:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_io.c:47:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_query.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_query.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/../hal/phydm/phydm_types.h:197,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/../hal/phydm/phydm_precomp.h:29,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/hal_data.h:20,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/../hal/phydm/phydm_types.h:197,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/../hal/phydm/phydm_precomp.h:29,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/hal_data.h:20,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_vht.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_vht.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ieee80211.c:20:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ieee80211.c:20:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_wlan_util.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_wlan_util.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_set.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_set.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_query.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:78,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mi.c:17:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
  252 | struct sha256_state {
      |        ^~~~~~~~~~~~
In file included from /usr/src/linux-headers-5.10.0-2-common/include/linux/filter.h:24,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/sock.h:59,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/tcp.h:19,
                 from /usr/src/linux-headers-5.10.0-2-common/include/linux/ipv6.h:88,
                 from /usr/src/linux-headers-5.10.0-2-common/include/net/addrconf.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service_linux.h:48,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/osdep_service.h:50,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/include/drv_types.h:27,
                 from /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mi.c:17:
/usr/src/linux-headers-5.10.0-2-common/include/crypto/sha.h:84:8: note: originally defined here
   84 | struct sha256_state {
      |        ^~~~~~~~~~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_security.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ieee80211.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_ioctl_set.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_wlan_util.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_cmd.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_io.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_vht.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_debug.o] Error 1
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mi.o] Error 1
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.c: In function ‘mgt_dispatcher’:
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.c:1887:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
 1887 |    ptable->func = &OnAuthClient;
      |    ~~~~~~~~~~~~~^~~~~~~~~~~~~~~
/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.c:1889:2: note: here
 1889 |  case WIFI_ASSOCREQ:
      |  ^~~~
make[3]: *** [/usr/src/linux-headers-5.10.0-2-common/scripts/Makefile.build:284: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/core/rtw_mlme_ext.o] Error 1
make[2]: *** [/usr/src/linux-headers-5.10.0-2-common/Makefile:1817: /var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build] Error 2
make[1]: *** [/usr/src/linux-headers-5.10.0-2-common/Makefile:185: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.10.0-2-amd64'
make: *** [Makefile:2188: modules] Error 2

''''''/var/lib/dkms/rtl8821CU/5.4.1_28754.r1/build/make.log''''''''''

**Comment by rockyprabowo** [comment]
Hi there, I'm sorry for the late response. Unfortunately, I don't have any device that uses this driver anymore so I can't really test any changes needed on my behalf. You can check and try to build the driver from another repository like [https://github.com/brektrou/rtl8821CU](https://github.com/brektrou/rtl8821CU), you just need to make sure that there is at least some work done to make the driver can be built against Linux 5.10.
Closing this and archiving this repositories.
